### ISSUE TITLE
1주차 [7/29 ~ 8/2] 엄지훈 TODO todo

### ISSUE THREAD

**Issue by 2Hojune** [KitsuneSiho/HOUSEKEEPING_BACKEND#11]
- [x] 1대1 및 그룹 채팅 기능을 소켓io를 활용해서 구현
- [x] 친구 목록 받아오기 및 소켓을 활용해서 로그인 중인 친구 목록 출력 기능 구현
- [x] 친구를 초대하여 채팅 방 만들기 기능 구현
- [x] 방 나가기, 방 사람  초대하기, 방 이름 바꾸기 등의 메뉴 기능 구현
- [x] 채팅 관련 페이지 디자인 수정
- [x] 인트로 애니메이션 제작
