### ISSUE TITLE
2주차 [8/5 ~ 8/9] 시호 TODO

### ISSUE THREAD

**Issue by KitsuneSiho** [KitsuneSiho/HOUSEKEEPING_BACKEND#16]
- [x] 의류분류 최종테스트
- [x] OCR 기능 사전공부
- [x] OCR 로직 구현
- [x] OCR 추출물 영수증 폼에 맞게 품목 추출(클로바AI or GPT API)
- [x] OCR 영수증 품목 추출 구현
