### ISSUE TITLE
2주차 [8/5 ~ 8/9] 엄지훈 TODO

### ISSUE THREAD

**Issue by 2Hojune** [KitsuneSiho/HOUSEKEEPING_BACKEND#25]
- [x] 소켓 io 를 사용하기 위한 Node.js 서버 생성
- [x] 소켓과 DB를 활용한 실시간 1대1, 그룹 채팅 기능 구현
- [x] 소켓과 DB를 활용한 접속중인 친구 목록 출력 기능 구현
