### ISSUE TITLE
3주차 [8/12 ~ 8/16] 강현욱 TODO

### ISSUE THREAD

**Issue by harrykang0805** [KitsuneSiho/HOUSEKEEPING_BACKEND#29]
- [x] 회원가입시, 마이페이지, 마이인포에 프로필사진 설정
- [x] RoomE Tip 게시판 CRUD 구현, 권한설정
- [x] 사용자 계정 레벨 시스템
