### ISSUE TITLE
3주차 [8/12 ~ 8/16] 엄지훈 TODO

### ISSUE THREAD

**Issue by djawlgns7** [KitsuneSiho/HOUSEKEEPING_BACKEND#31]
- [x] 네이버 클라우드에 프로젝트 호스팅
- [x] SSL 인증서를 획득하여 보안 강화
- [ ] CI/CD 파이프라인 생성 
- [x] 호스팅 후 발생하는 버그 수정
