### ISSUE TITLE
1주차 [7/29 ~ 8/2] 강현욱 TODO

### ISSUE THREAD

**Issue by harrykang0805** [KitsuneSiho/HOUSEKEEPING_BACKEND#7]
- [x] 시큐리티 기본설정
- [x] jwt 레퍼런스 구축
- [ ] 백엔드와 프론트엔드 토큰연결 (ing)
- [ ] 프론트엔드에서 jwt 정보 불러와서 출력 (ing)
