### ISSUE TITLE
1주차 [7/29 ~ 8/2] 시호 TODO

### ISSUE THREAD

**Issue by KitsuneSiho** [KitsuneSiho/HOUSEKEEPING_BACKEND#8]
- [x] Linux 서버 구축
- [x] 머신러닝 모델 공부
- [x] 머신러닝 환경구축
- [x] 데이터세트 수집
- [x] 데이터셋 훈련
- [x] F테스트 시행 및 정확도 80% 이상 출력
- [x] 1
- [x] 1
- [x] 1
- [x] 1
